apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: catalogue
  name: catalogue
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: catalogue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
