apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: ratings
  name: ratings
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: ratings
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
